import { createCipheriv, createDecipheriv, randomBytes } from "crypto";

// AES-256-GCM symmetric encryption for storing third-party OAuth tokens at rest.
// The key (INTEGRATION_TOKEN_KEY) is a 32-byte (64 hex char) value generated by
//   openssl rand -hex 32
// Encrypted strings are stored as `iv:tag:ciphertext` hex triples.

const ALG = "aes-256-gcm";
const IV_LEN = 12;       // GCM recommended IV length
const TAG_LEN = 16;      // GCM auth tag length

function getKey(): Buffer {
  const hex = process.env.INTEGRATION_TOKEN_KEY;
  if (!hex || hex.length !== 64) {
    throw new Error(
      "INTEGRATION_TOKEN_KEY must be set to a 32-byte hex string (run: openssl rand -hex 32)"
    );
  }
  return Buffer.from(hex, "hex");
}

/** Encrypt a UTF-8 string. Returns `iv:tag:ciphertext` hex, or null on null input. */
export function encryptSecret(plain: string | null | undefined): string | null {
  if (plain == null || plain === "") return null;
  const key = getKey();
  const iv = randomBytes(IV_LEN);
  const cipher = createCipheriv(ALG, key, iv);
  const ct = Buffer.concat([cipher.update(plain, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return `${iv.toString("hex")}:${tag.toString("hex")}:${ct.toString("hex")}`;
}

/** Decrypt a value produced by encryptSecret(). Returns null on failure or null input. */
export function decryptSecret(payload: string | null | undefined): string | null {
  if (!payload) return null;
  try {
    const parts = payload.split(":");
    if (parts.length !== 3) return null;
    const [ivHex, tagHex, ctHex] = parts;
    const iv = Buffer.from(ivHex, "hex");
    const tag = Buffer.from(tagHex, "hex");
    const ct = Buffer.from(ctHex, "hex");
    if (iv.length !== IV_LEN || tag.length !== TAG_LEN) return null;
    const decipher = createDecipheriv(ALG, getKey(), iv);
    decipher.setAuthTag(tag);
    const pt = Buffer.concat([decipher.update(ct), decipher.final()]);
    return pt.toString("utf8");
  } catch (err) {
    console.error("[crypto] decryptSecret failed:", err);
    return null;
  }
}
